# Generated by Django 6.0 on 2025-12-05 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255, unique=True)),
                ("x", models.IntegerField(null=True)),
                ("y", models.IntegerField(null=True)),
            ],
            options={
                "unique_together": {("x", "y")},
            },
        ),
        migrations.CreateModel(
            name="MobileSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_2g", models.BooleanField()),
                ("has_3g", models.BooleanField()),
                ("has_4g", models.BooleanField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="app.location",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.operator"),
                ),
            ],
        ),
    ]
